### ISSUE TITLE
Release 0.1.0 tracking issue

### ISSUE THREAD

**Issue by iduartgomez** [iduartgomez/tf-rs#3]
Master issue to track tasks related to 0.1.0 release.

- [ ] Parity with C++ ops bindings.
- [ ] Tests and examples for all ops.
- [ ] Tests for high level functionality (scope management, namescope creation/collision).
